server:
  port: 8082
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital?useSSL=false&allowPublicKeyRetrieval=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
     
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  application:
    name: patient-service
  jackson:
    date-format: dd-MM-yyyy
    
    
    serialization:
      write-dates-as-timestamps: false
    


